#!/bin/bash
# Update the yum cache files in (default) /var/cache/ecf-global, for future
# parsing.

CONFIG=/etc/ecf-global/yum-cache.yaml

if [ ! -r $CONFIG ] ;then
    echo "cannot read $CONFIG, aborting"
    exit -1
fi

OUTDIR=`cat $CONFIG | shyaml get-value cachedir`
CHECK_CMD=`cat $CONFIG | shyaml get-value check_cmd`
CHECK_CMD_TIMEOUT=`cat $CONFIG | shyaml get-value check_cmd_timeout`

/usr/libexec/ecf-global/timeout3 -t 60 $CHECK_CMD > $OUTDIR/yum-cache.log
echo "$?" > $OUTDIR/yum-cache.status
