#!/bin/bash
# Wrapper for 'puppet agent -t'; see the documentation below.

#########################################################################
### Configuration #######################################################
#########################################################################

## Default values for parts of the puppet agent -t run
DOIT="--noop"
EXTRA=""

#########################################################################
### main () #############################################################
#########################################################################

## Parse command-line variables
TEMP=`/usr/bin/getopt -n "$0" \
    -o hs:e: \
    --long help,man,doit,force,trace,environment:,server:,tags: \
    -- "$@"`

if [ $? != 0 ] ; then
    echo "getopt failed..." >&2 ;
    exit -1
fi

eval set -- "$TEMP"

while true; do
    case "$1" in
        -h|--help|--man)
            exec pod2text $0
            exit 0
            ;;
        --doit)
            DOIT=""
            shift
            ;;
        --force)
            EXTRA="${EXTRA} --agent_disabled_lockfile=foo.lock"
            shift
            ;;
        -e|--environment)
            EXTRA="${EXTRA} --environment $2"
            shift 2
            ;;
        -s|--server)
            EXTRA="${EXTRA} --server $2 --srv_domain="
            shift 2
            ;;
        --tags)
            EXTRA="${EXTRA} --tags $2"
            shift 2
            ;;
        --trace)
            EXTRA="${EXTRA} --evaltrace"
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "unknown argument: $1"
            exec pod2text $0
            exit -1
    esac
done

if [ $# -ne 0 ] ; then # extra arguments
    exec pod2text $0
    exit -1
fi

echo puppet agent -t $EXTRA $DOIT
exec puppet agent -t $EXTRA $DOIT

#########################################################################
### Documentation #######################################################
#########################################################################

# Documentation.  Use a hack to hide this from the shell.  Because of the
# above exit line, this should never be executed.

DOCS=<<__END_OF_DOCS__

=head1 NAME

puppet-dryrun - wrapper for 'puppet agent -t'

=head1 SYNOPSIS

puppet-dryrun

puppet-dryrun --environment I<environment>

puppet-dryrun --server I<server>

puppet-dryrun --tags I<tags>

puppet-dryrun --environment I<environment> --doit

=head1 DESCRIPTION

puppet-dryrun is a simple wrapper around I<puppet agent -t>

=head1 OPTIONS

=over 4

=item B<--doit>

Do not run with the B<--noop> flag.  Default is to keep the B<--noop>

=item B<--environment> I<ENVIRONMENT>

Run against a specific environment.  No default.

=item B<--force>

Ignore any existing lockfile, so you can run a dryrun even when the host is
locked.  Use this sparingly!

=item B<--server> I<SERVER>

Run against a specific server.  No default.

=item B<--trace>

Set B<--evaltrace> on run.  Default off.

=item B<--tags> I<TAGS>

Only run the specified tags.  No default (which means 'run everything').

=item B<--help>, B<--man>

Print this help page.

=back

=head1 AUTHOR

Tim Skirvin <tskirvin@fnal.gov>

=head1 LICENSE

Copyright 2014-2024, Fermi National Accelerator Laboratory

This program is free software; you may redistribute it and/or modify it
under the same terms as Perl itself.

=cut

__END_OF_DOCS__
