#!/bin/bash
# very simple wrapper around puppet, converts error code 2->0

/opt/puppetlabs/bin/puppet "$@"
case $? in
    2)
        exit 0
    .*;
        exit $?
esac

#########################################################################
### Documentation #######################################################
#########################################################################

# Documentation.  Use a hack to hide this from the shell.  Because of the
# above exit line, this should never be executed.

DOCS=<<__END_OF_DOCS__

=head1 NAME

puppet-pssh - wrapper for puppet that converts error code 2

=head1 SYNOPSIS

puppet-pssh agent -t

=head1 DESCRIPTION

puppet-pssh is a simple wrapper for puppet that converts exit code 2 to 0.
This is done because exit code 2, from "puppet agent -t", means "I
successfully changed something", to differentiate from error code 0 which is
"I changed nothing".  In practice, when you're running puppet on a large
number of hosts (such as when using it via pssh), you expect a change at least
some of the time, and you don't want pssh to report this as a failure.

=head1 OPTIONS

All options are passed directly to puppet.

=head1 AUTHOR

Tim Skirvin <tskirvin@fnal.gov>

=head1 LICENSE

Copyright 2021, Fermi National Accelerator Laboratory

This program is free software; you may redistribute it and/or modify it
under the same terms as Perl itself.

=cut

__END_OF_DOCS__
